---
version: '3'
services:
    pub1:
        image: centos6/epas10:latest
        build:
          context: ../../epas
          dockerfile: Dockerfile.centos6
          args:
            YUMUSERNAME: ${YUMUSERNAME}
            YUMPASSWORD: ${YUMPASSWORD}
            PGMAJOR: 10
        container_name: pub1
        hostname: pub1
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - ".:/docker"
        networks:
            public:
                ipv4_address: 10.111.220.12
        entrypoint:
          - "/docker/entrypoint.sh"

    mdn:
        image: xdb:latest
        build:
          context: ../6.2
          args:
            PGMAJOR: 10
        container_name: mdn
        hostname: mdn
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - ".:/docker"
          - "/tmp/.X11-unix:/tmp/.X11-unix"
        networks:
            public:
                ipv4_address: 10.111.220.11
        environment:
          - "DISPLAY=host.docker.internal:0"
        depends_on:
          - pub1
        entrypoint:
          - "/docker/entrypoint.sh"

networks:
    public:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.220.1/24
